import "~/styles/globals.css";

import { type Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { cn } from "~/lib/utils";
import { DesktopVerticalNav } from "./_components/navigation";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "~/components/ui/common/avatar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("antialised bg-muted/40 font-sans", fontSans.variable)}
      >
        <TRPCReactProvider>
          <div className="flex max-h-screen min-h-screen flex-col">
            <div className="flex-0 relative flex items-center justify-between border-b bg-background px-6 py-2">
              <div className="py-4">
                <span>Desk Booking app</span>
              </div>
              <Avatar>
                <AvatarImage />
                <AvatarFallback>NA</AvatarFallback>
              </Avatar>
            </div>
            <div className="flex flex-1 overflow-y-hidden">
              <div className="flex border-r bg-background p-4">
                <DesktopVerticalNav />
              </div>
              <div className="flex grow rounded p-6">{children}</div>
            </div>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
